version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: database_container
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgres
      - ./postgres/db.sql:/docker-entrypoint-initdb.d/db.sql
    