version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: database_container
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgres
      - ./postgres/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - network-lb
  
  lib_back:
    build: .
    container_name: backend_container
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./library_back:/code
    depends_on:
      - db
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    networks:
      - network-lb
  
  lib_front:
    container_name: frontend_container
    restart: always
    build: ../library_front
    ports:
      - 3000:3000
    depends_on:
      - lib_back
    volumes:
      - ../library_front:/library_front
    networks: 
      - network-lb

  lib_nginx:
      image: nginx:1.22.0-alpine
      container_name: nginx_container
      restart: always
      ports:
        - 3008:3008
      volumes:
        - ../nginx.conf:/etc/nginx/nginx.conf
      links:
        - lib_front
      depends_on:
        - lib_front
      networks:
        - network-lb

networks:
  network-lb:
    driver: bridge